### ISSUE TITLE
Cargo not working

### ISSUE THREAD

**Issue by QuentinN42** [DIS-Wolv/ODD#36]

**Comment by QuentinN42** [comment]
Always working in solo, never on server...

**Comment by QuentinN42** [comment]
There is two functions : [setSpace](https://github.com/acemod/ACE3/blob/8517a6ef73a826625da6ef57845187b9397f74af/addons/cargo/functions/fnc_setSpace.sqf#L15) and [setSize](https://github.com/acemod/ACE3/blob/8517a6ef73a826625da6ef57845187b9397f74af/addons/cargo/functions/fnc_setSize.sqf#L16) but it seems working some times.

**Comment by QuentinN42** [comment]
Peut etre du aux lags sur le serveur, ajouter un petit sleep fix peut etre le truc ...

**Comment by DIS-Wolv** [comment]
localité ?

**Comment by DIS-Wolv** [comment]
> Always working in solo, almost never on server...

Localité !

**Comment by DIS-Wolv** [comment]
cargo set ici : 
https://github.com/DIS-Wolv/ODD/blob/fe46121c7c4ef2ca8cfb7d5f39533422c4c9bc96/template_functions/WOLV_Garage/fn_aceInvSetSize.sqf#L25C46-L25C46
wiki sur le github ace : 
https://github.com/acemod/ACE3/blob/master/docs/wiki/framework/cargo-framework.md#43-adjusting-cargo-space-of-a-vehicle
> Set the cargo space of any object. **Has global effect.**
peux etre pas si global que ca ?
probleme d'apres moi : Localité 
raison possible :
 - fonction : obj local, effect global => executé sur un obj remote
 - fonction : obj local, effect local => executé sur un obj remote ou que pour un joueur 
 piste de correction *remoteexec* avec comme argument [XX, 0, True] ?
 - XX => commande
 - 0 => tout le monde
 - True => répéter pour les JIP
remoteExec sur le wiki : https://community.bistudio.com/wiki/remoteExec

**Comment by DIS-Wolv** [comment]
> Peut etre du aux lags sur le serveur, ajouter un petit sleep fix peut etre le truc ...

possible apres il y a deja un delay a cause de l'ajout des items dans l'inventaire : 
https://github.com/DIS-Wolv/ODD/blob/fe46121c7c4ef2ca8cfb7d5f39533422c4c9bc96/template_functions/WOLV_Garage/fn_garSpawnVl.sqf#L12-L69

**Comment by DIS-Wolv** [comment]
https://github.com/acemod/ACE3/pull/9481
